#EXERCISE
##applying k means clustering to the new data generated by the PCA

##make new data from the PCA scores of the original data
##load the data --- wine quality data

data1 <- read.csv(file.choose(), header = T, sep = ",")

##remove the unwanted variables

data2 <- data1[,-12]


##scale the data using scale function

data3 <- scale(data2, center = TRUE , scale = TRUE)


##implement the principal component analysis using princomp from stats

pcamodel <- princomp(data3, scores = T, cor = T)

summary(pcamodel)

##show the loadings -- or the eigenvector for each component

loadings(pcamodel)

##plot the components
plot(pcamodel)
screeplot(pcamodel, type = "line", main = "Scree Plot") ## "main" is the title of the graph

##show the biplot for further analysis
biplot(pcamodel)

#get the desired number of components based on the visualization and summary, in this case 6 components
#get the scores of the original data given the components
datanew <- pcamodel$scores[,1:6]

View(datanew)

#apply k means clustering
kmean <- kmeans(datanew, 7)

##to view the resulting clusters
kmean$cluster

##compare the resulting cluster to the actual classification (data1$quality):
table1 <- table(data1$quality, kmean$cluster)

table1

##plot the clusters using ggplot2
library(ggplot2)

#add the result$cluster to the kdata
cluster <- as.data.frame(factor(kmean$cluster))
nrow(cluster)
kdata2 <- as.data.frame(cbind(datanew, kmean$cluster))
names(kdata2)[7] <- "newcluster"

head(kdata2)

##make a graph
g <- ggplot(data = kdata2, aes(x=kdata2$Comp.1, y=kdata2$Comp.2, col = factor(kdata2$newcluster))) + geom_point()
g
##show the centroids using the result$centers
centroid <-as.data.frame(kmean$centers)

g1 <- g + geom_point(data=centroid, colour = "#696969", aes(x=centroid$Comp.1, y=centroid$Comp.2)) + geom_point(data=centroid, colour = "#696969", aes(x=centroid$Comp.1, y=centroid$Comp.2), size=50, alpha=.5)
g1



